def print_temperature_help():
    print("---Temperature Help---")
    print("") 
    print("Call this program with the argument of temp to convert temperatures")
    print("The following argument will be ?2? where each question mark")
    print("represents the temperature scale you wish to convert from and to.")
    print("The following temperature converstions are supported:")
    print("(C)elsius")
    print("(F)ahrenheit")
    print("(K)elvins")
    print("(R)ankines")
    print("For example, to convert Celsius to Fahrenheit, you can invoke")
    print("the tool with the following command:")
    print("") 
    print("python3 conv.py temp c2f 20")
    print("")
    print("Use python3 conv.py help to get additional help on the usage")
    print("of this tool.")


def print_length_help():
    print("---Length Help---")
    print("")
    print("Call this program with the argument of length to convert units of")
    print("length. Various convertions to meters can be done from other metric")
    print("units of length by simply specifying the unit you want to convert")
    print("from. For instance, you can convert from micrometers to meters with")
    print("the following:")
    print("")
    print("python3 conv.py length μm 100000")
    print("")
    print("For supported metric units, use python3 conv.py help metric")
    print("For other supported units, use python3 conv.py help lengths")

def print_metric_help():
    print("---Metric Help---")
    print("") 
    print("The following metric units, smallest to largest, are supported for conversions:")
    print("")
    print("Yoctometer: ym")
    print("Zeptometer: zm")
    print("Attometer: am")
    print("Femtometer: fm")
    print("Picometer: pm")
    print("Nanometer: nm")
    print("Micrometer: μm")
    print("Millimeter: mm")
    print("Centimeter: cm")
    print("Decimeter: dm")
    print("Decameter: dam")
    print("Hectometer: hm")
    print("Kilometer: km")
    print("Megameter: Mm")
    print("Gigameter: Gm")
    print("Terameter: Tm")
    print("Petameter: Pm")
    print("Exameter: Em")
    print("Zettameter: Zm")
    print("Yottameter: Ym")
    print("Ronnameter: Rm")

def print_lengths_help():
    print("---Non-metric lengths help---")
    print("")
    print("The following non-metric lengths can be converted with this tool:")
    print("")
    print("None currently supported.")

def print_units_help():
    print("---Units help---")
    print("")
    print("The following unit types are currently supported:")
    print("")
    print("temperature")
    print("length")

def print_command_help():
    print("Usage: python3 conv.py [unit type] [conversion type] [quanity]")
    print("")
    print("Use pyton3 conv.py help units for valid unit types.")
    print("Use pyton3 conv.py help [unit type] for valid conversion types")
    print("[quantity] is the amount of something you want to convert.")
    print("")
    print("Version 0.1.0")

